#cms系统微服务层的配置
server:
  port: 31001

spring:
  application:
    name: sfs-service-manage-cms

  #连接mongodb数据库
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017    #url默认本地端口为27017
      database: sfs_cms                       #配置连接数据库

  freemarker:
    cache: false        #关闭模板缓存，方便测试
    settings:
      classic_compatible: true
      template_update_delay: 0          #检查模板更新延迟时间，设置为0立即检查

  #rabbitmq的配置
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    virtual-host: /

eureka:
  client:
    register-with-eureka: true  #服务注册开关
    fetch-registry: true        #服务发现开关

    service-url:
        defaultZone: http://localhost:50101/eureka/       #eureka服务端的地址
  instance:
    prefer-ip-address: true      #将自己的ip注册到eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}  #指定实例名以及端口
